# Generated by Django 5.2.6 on 2026-03-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('products', '0002_alter_product_discount_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='coupon',
            name='category',
            field=models.ManyToManyField(blank=True, to='products.productscategory'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='products',
            field=models.ManyToManyField(blank=True, to='products.product'),
        ),
    ]
