# Generated by Django 5.2.6 on 2026-03-13 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_webhookevent_alter_coupon_category_and_more'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_orders', to='logistics.dispatch'),
        ),
    ]
