# Generated by Django 5.2.6 on 2026-04-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_remove_order_shipping_cost_address_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_distance',
            field=models.FloatField(default=0),
        ),
    ]
