# Generated by Django 5.2.6 on 2026-03-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_order_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancel_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancel_pin_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
