# Generated by Django 5.2.6 on 2026-03-15 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_order_cancel_pin_order_cancel_pin_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cancel_pin',
        ),
        migrations.RemoveField(
            model_name='order',
            name='cancel_pin_created_at',
        ),
    ]
