# Generated by Django 5.2.6 on 2026-04-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='cost_per_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
